#########################################################################
# Title:            Sandbox: promtail                                   #
# Author(s):        notarealemail                                       #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: "Settings | Import promtail-config.yml"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: '{{ promtail_paths_location }}/config/{{ item }}'
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"
    force: yes
  loop:
    - "promtail-config.yml"
  when: promtail_overwrite_config

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
